---
dataset:
  small_df: True
  include_tasks: False
  batch_size: 4000

model:
  name: "Utilization LSTM Model without Tasks"
  save_model: True
  num_epochs: 100
  learning_rate: 0.0002
  hidden_size: 8000
  num_layers: 2

  scheduler:
    patience: 50
    factor: 0.5
    min_lr: 0.00001
    eps: 0.000000001

evaluation_path:
  save_to_file: True
  loss_progression: "evaluation/task_vs_no_task/loss_progression_no_tasks.csv"
  training_prediction_path: "evaluation/task_vs_no_task/util_lstm_train_no_tasks.csv"
  test_prediction_path: "evaluation/task_vs_no_task/util_lstm_test_no_tasks.csv"

logging:
  enable_wandb: False

