---
dataset:
  small_df: True
  include_tasks: False
  batch_size: 500

model:
  name: "Utilization LSTM Model Machine"
  save_model: True
  num_epochs: 100
  learning_rate: 0.0001
  hidden_size: 6500
  num_layers: 3

  scheduler:
    patience: 50
    factor: 0.5
    min_lr: 0.00001
    eps: 0.000000001

evaluation_path:
  save_to_file: True
  training_prediction_path: "evaluation/task_vs_no_task/machine_training_eval.csv"
  test_prediction_path: "evaluation/task_vs_no_task/machine_test_eval.csv"

logging:
  enable_wandb: False